# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

apt_packages:
  - libtiff4-dev
  - xsel

r_github_packages:
  - rorynolan/strex
  - rorynolan/filesstrings
  - ropensci/ijtiff

after_success:
  - Rscript -e 'covr::codecov()'
